# Generated by Django 6.0.4 on 2026-05-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_is_profile_complete_user_is_user_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_user_complete',
            new_name='is_profile_complete',
        ),
    ]
