# Generated by Django 6.0.4 on 2026-06-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_profile_complete',
        ),
    ]
